### ISSUE TITLE
Revisar funcionament PortaFIB 2.2 amb JBoss 7.2

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#706]
Revisar funcionament PortaFIB 2.2 amb JBoss 7.2

- [x]  Arreglar Pantalla de Vista Completa de Destinatari #707 
- [x]  Adaptar classes CSS de Bootstrap 3 a BootStrap 4 #708
- [x]   Revisar totes les opcions del Menu Inici de PortaFIB Back #709
- [x]  La icona per tancar l'Agrupació existeix però no es visible #710 
- [x]  Eliminació múltiple es permet encara que no hi hagi cap element seleccionat. #711
