### ISSUE TITLE
Ampliar els Modes de Firma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#825]
Ampliar els Modes de Firma

- [x] PluginsIb de Validació de Firmes:  [Adaptar Modes de Firma de String a Integer #35](https://github.com/GovernIB/pluginsib-validatesignature/issues/35)
- [x] Aplicar nous Modes de Firma de Plugins de Firma en Servidor i  Plugins de Firma Web: Ampliar el Modes de Firma del Plugins de Firma en Servidor i Firma Web
[#905](https://github.com/GovernIB/portafib/issues/905)
- [x] Ampliar els modes de firma de PortaFIB (SIGN_MODE)
[#813](https://github.com/GovernIB/portafib/issues/813)

![321144250-f0e42ebe-b24f-4939-893d-54932833d1ed](https://github.com/GovernIB/portafib/assets/17084256/05e732e0-2411-499f-95e4-96db8c007c10)

https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/doc/dss-documentation.html#SignatureProfileGuide

**Comment by anadal-fundaciobit** [comment]
Acabades totes les tasques Associades.
