### ISSUE TITLE
Ampliar el Modes de Firma del Plugins de Firma en Servidor i Firma Web

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#905]
Ampliar el Modes de Firma del Plugins de Firma en Servidor i Firma Web

- [ ]  [Nou Mòdul per centralitzar constants i utilitats de Signatura](https://github.com/GovernIB/pluginsib-utils/issues/16)
- [ ] Ampliar el Modes de Firma del Plugins de Firma en Servidor https://github.com/GovernIB/pluginsib-signatureserver/issues/6
- [ ] Ampliar el Modes de Firma del Plugins de Firma en Web:  [Utilitzar constants de pluginsib-utils/signature i normalitzar Modes de Firma ](https://github.com/GovernIB/pluginsib-signatureweb/issues/13)

**Comment by anadal-fundaciobit** [comment]
Solucionat
